apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-vllm-mistral-7b
  labels:
    app: triton-vllm-mistral-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-vllm-mistral-7b
  template:
    metadata:
      labels:
        app: triton-vllm-mistral-7b
    spec:
      containers:
      - name: triton-server
        image: triton-vllm-mistral-7b:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        env:
        - name: TRITON_MODEL_REPOSITORY
          value: "/models"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "4"
          limits:
            nvidia.com/gpu: 1
            memory: "24Gi"
            cpu: "8"
        readinessProbe:
          httpGet:
            path: /v2/health/ready
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /v2/health/live
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 3
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: triton-vllm-mistral-7b-service
  labels:
    app: triton-vllm-mistral-7b
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: grpc
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: metrics
  selector:
    app: triton-vllm-mistral-7b
