apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-mistral-7b-neuron
  labels:
    app: vllm-mistral-7b-neuron
    version: vllm-neuron-dlc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-mistral-7b-neuron
  template:
    metadata:
      labels:
        app: vllm-mistral-7b-neuron
        version: vllm-neuron-dlc
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: inf2.8xlarge
      tolerations:
      - key: aws.amazon.com/neuron
        operator: Exists
        effect: NoSchedule
      containers:
      - name: vllm-server
        image: 820537372947.dkr.ecr.us-west-2.amazonaws.com/vllm-mistral-7b-neuron:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MODEL_ID
          value: "mistralai/Mistral-7B-Instruct-v0.3"
        - name: DEVICE
          value: "neuron"
        - name: TENSOR_PARALLEL_SIZE
          value: "2"
        - name: MAX_NUM_SEQS
          value: "4"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugging-face-token
              key: token
        resources:
          requests:
            aws.amazon.com/neuron: 1
          limits:
            aws.amazon.com/neuron: 1
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-mistral-7b-neuron
  labels:
    app: vllm-mistral-7b-neuron
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: vllm-mistral-7b-neuron
